"""empty message

Revision ID: 399bf32a2a75
Revises: b1a098ab9d8c
Create Date: 2026-01-29 18:06:11.584136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "399bf32a2a75"
down_revision: Union[str, Sequence[str], None] = "b1a098ab9d8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slash_commands",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "mode",
            sa.String(length=20),
            server_default=sa.text("'raw'"),
            nullable=False,
        ),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("argument_hint", sa.String(length=255), nullable=True),
        sa.Column("allowed_tools", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("raw_markdown", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_slash_command_user_name"),
    )
    op.create_index(
        op.f("ix_slash_commands_user_id"), "slash_commands", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_slash_commands_user_id"), table_name="slash_commands")
    op.drop_table("slash_commands")
    # ### end Alembic commands ###
