"""empty message

Revision ID: b1a098ab9d8c
Revises: e1c0ccb93e57
Create Date: 2026-01-29 17:47:22.698404

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1a098ab9d8c"
down_revision: Union[str, Sequence[str], None] = "e1c0ccb93e57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usage_logs", sa.Column("run_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_usage_logs_run_id"), "usage_logs", ["run_id"], unique=False
    )
    op.create_foreign_key(
        "fk_usage_logs_run_id",
        "usage_logs",
        "agent_runs",
        ["run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_usage_logs_run_id", "usage_logs", type_="foreignkey")
    op.drop_index(op.f("ix_usage_logs_run_id"), table_name="usage_logs")
    op.drop_column("usage_logs", "run_id")
    # ### end Alembic commands ###
